-- Criação da tabela para as áreas de atuação
--(Viseu,Tomar,Fundão,Portalegre,Vila Real)
CREATE TABLE TABELA_POSTO (
    ID_POSTO INT PRIMARY KEY,
    NOME_POSTO VARCHAR(255) NOT NULL
);

-- Criação da tabela de áreas de atuação
--(7 Áreas: Saúde, Desporto, Formação, Gastronomia, Habitação/Alojamento, Transportes ,Lazer)
CREATE TABLE TABELA_AREA (
    ID_AREA INT PRIMARY KEY IDENTITY(1,1),
    NOME_AREA VARCHAR(255) NOT NULL
);

-- Criação da tabela de utilizadores
CREATE TABLE TABELA_UTILIZADOR (
    ID_UTILIZADOR INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255),
    NIF VARCHAR(20),
    ID_POSTO INT FOREIGN KEY REFERENCES TABELA_POSTO(ID_POSTO),
    TELEMOVEL VARCHAR(20),
    EMAIL VARCHAR(255) UNIQUE,
    PALAVRA_PASSE VARCHAR(255),
    ESTADO BOOLEAN DEFAULT 0,
    ID_GOOGLE VARCHAR(255),
    TOKEN_GOOGLE VARCHAR(255),
    ID_FACEBOOK VARCHAR(255),
    TOKEN_FACEBOOK VARCHAR(255),
    CARGO VARCHAR(255),
    TIPO_UTILIZADOR BIT DEFAULT 0,
    AREAS_INTERESSE VARCHAR(MAX)
);

-- Criação da tabela de administradores
CREATE TABLE TABELA_ADMIN (
    ID_ADMIN INT PRIMARY KEY IDENTITY(1,1),
    ID_UTILIZADOR INT FOREIGN KEY REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR)
);

-- Criação da tabela de colaboradores
CREATE TABLE TABELA_COLABORADOR (
    ID_COLAB INT PRIMARY KEY IDENTITY(1,1),
    ID_ADMIN INT FOREIGN KEY REFERENCES TABELA_ADMIN(ID_ADMIN),
    ID_UTILIZADOR INT FOREIGN KEY REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR)
);

-- Criação da tabela de subáreas
CREATE TABLE TABELA_SUBAREA (
    ID_SUBAREA INT PRIMARY KEY IDENTITY(1,1),
    ID_AREA INT FOREIGN KEY REFERENCES TABELA_AREA(ID_AREA),
    NOME_SUBAREA VARCHAR(255) NOT NULL
);


-- Criação da tabela de eventos
CREATE TABLE TABELA_EVENTO (
    ID_EVENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_AREA INT FOREIGN KEY REFERENCES TABELA_AREA(ID_AREA),
    ID_SUBAREA INT FOREIGN KEY REFERENCES TABELA_SUBAREA(ID_SUBAREA),
    ID_COLAB INT FOREIGN KEY REFERENCES TABELA_COLABORADOR(ID_COLAB),
    ID_POSTO INT FOREIGN KEY REFERENCES TABELA_POSTO(ID_POSTO),
    TITULO_EVENTO VARCHAR(255) NOT NULL,
    DESCRICAO_EVENTO TEXT NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    LOCALIZACAO VARCHAR(255),
    ID_ADMIN INT FOREIGN KEY REFERENCES TABELA_ADMIN(ID_ADMIN)
);

-- Criação da tabela de Estabelecimentos
CREATE TABLE TABELA_ESTABELECIMENTOS (
    ID_ESTABELECIMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255),
    ID_AREA INT FOREIGN KEY (ID_AREA) REFERENCES TABELA_AREA(ID_AREA),
    ID_SUBAREA INT FOREIGN KEY (ID_SUBAREA) REFERENCES TABELA_SUBAREA(ID_SUBAREA),
    ID_POSTO INT FOREIGN KEY (ID_POSTO) REFERENCES TABELA_POSTO(ID_POSTO),
    LOCALIZACAO VARCHAR(255),
    DESCRICAO TEXT,
);

-- Criação da tabela de fórunsS
CREATE TABLE TABELA_FORUM (
    ID_FORUM INT PRIMARY KEY IDENTITY(1,1),
    ID_EVENTO INT FOREIGN KEY REFERENCES TABELA_EVENTO(ID_EVENTO),
    TITULO_FORUM VARCHAR(255) NOT NULL,
    DESCRICAO_FORUM TEXT NOT NULL
);

-- Criação da tabela de comentários de eventos
CREATE TABLE TABELA_COMENTARIO (
    ID_COMENTARIO INT PRIMARY KEY IDENTITY(1,1),
    ID_FORUM INT REFERENCES TABELA_FORUM(ID_FORUM),
    ID_UTILIZADOR INT REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR),
    TEXTO_COMENTARIO TEXT NOT NULL,
    DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_ADMIN INT FOREIGN KEY REFERENCES TABELA_ADMIN(ID_ADMIN)
);

-- Criação da tabela de inscrições em eventos
CREATE TABLE TABELA_INSCRICAO_EVENTO (
    ID_INSCRICAO INT PRIMARY KEY IDENTITY(1,1),
    ID_EVENTO INT REFERENCES TABELA_EVENTO(ID_EVENTO),
    ID_UTILIZADOR INT REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR),
    DATA_INSCRICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_INSCRICAO VARCHAR(255) NOT NULL
);


-- Criação da tabela de classificações de eventos
CREATE TABLE TABELA_CLASSIFICACAO_EVENTO (
    ID_CLASSIFICACAO INT PRIMARY KEY IDENTITY(1,1),
    ID_EVENTO INT REFERENCES TABELA_EVENTO(ID_EVENTO),
    ID_UTILIZADOR INT REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR),
    CLASSIFICACAO INT CHECK (CLASSIFICACAO > 0 AND CLASSIFICACAO <= 5) NOT NULL,
    DATA_CLASSIFICACAO TIMESTAMP NOT NULL
);


-- Criação da tabela de formulários
CREATE TABLE TABELA_FORMULARIO (
    ID_FORMULARIO INT PRIMARY KEY IDENTITY(1,1),
    TITULO_FORMULARIO VARCHAR(255) NOT NULL,
    ID_EVENTO INT FOREIGN KEY REFERENCES TABELA_EVENTO(ID_EVENTO),
    DESCRICAO_FORMULARIO TEXT NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    ESTADO BOOLEAN DEFAULT 0
);

-- Criação da tabela de perguntas
CREATE TABLE TABELA_PERGUNTA (
    ID_PERGUNTA INT PRIMARY KEY IDENTITY(1,1),
    ID_FORMULARIO INT FOREIGN KEY REFERENCES TABELA_FORMULARIO(ID_FORMULARIO),
    TIPO_PERGUNTA VARCHAR(20) NOT NULL,
    TEXTO_PERGUNTA VARCHAR(255) NOT NULL,
    ORDEM_PERGUNTA INT NOT NULL
);

-- Criação da tabela de respostas
CREATE TABLE TABELA_RESPOSTA (
    ID_RESPOSTA INT PRIMARY KEY IDENTITY(1,1),
    ID_UTILIZADOR INT FOREIGN KEY REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR),
    ID_PERGUNTA INT FOREIGN KEY REFERENCES TABELA_PERGUNTA(ID_PERGUNTA),
    ID_INSCRICAO INT FOREIGN KEY REFERENCES TABELA_INSCRICAO_ATIVIDADE(ID_INSCRICAO),
    TEXTO_RESPOSTA TEXT
);

-- Criação da tabela de opções de resposta
CREATE TABLE TABELA_OPCAO_RESPOSTA (
    ID_OPCAO INT PRIMARY KEY IDENTITY(1,1),
    ID_PERGUNTA INT FOREIGN KEY REFERENCES TABELA_PERGUNTA(ID_PERGUNTA),
    TEXTO_OPCAO VARCHAR(255) NOT NULL,
    ORDEM_OPCAO INT NOT NULL
);

-- Criação da tabela de álbuns
CREATE TABLE TABELA_ALBUM (
  ID_ALBUM INT PRIMARY KEY IDENTITY(1,1),
  ID_EVENTO INT FOREIGN KEY REFERENCES TABELA_EVENTO(ID_EVENTO),
  TITULO_ALBUM VARCHAR(255) NOT NULL,
  DESCRICAO_ALBUM TEXT NOT NULL,
  DATA_CRIACAO DATE NOT NULL
);

-- Criação da tabela de fotos
CREATE TABLE TABELA_FOTO (
  ID_FOTO INT PRIMARY KEY IDENTITY(1,1),
  ID_ALBUM INT FOREIGN KEY REFERENCES TABELA_ALBUM(ID_ALBUM),
  ID_UTILIZADOR INT FOREIGN KEY REFERENCES TABELA_UTILIZADOR(ID_UTILIZADOR),
  TITULO_FOTO VARCHAR(255) NOT NULL,
  DESCRICAO_FOTO TEXT NOT NULL,
  DATA_UPLOAD DATE NOT NULL
);

---------------------------------------------------------------------------------------

--Eliminação das tabelas

DROP TABLE IF EXISTS TABELA_FOTO;
DROP TABLE IF EXISTS TABELA_ALBUM;
DROP TABLE IF EXISTS TABELA_OPCAO_RESPOSTA;
DROP TABLE IF EXISTS TABELA_RESPOSTA;
DROP TABLE IF EXISTS TABELA_PERGUNTA;
DROP TABLE IF EXISTS TABELA_FORMULARIO;
DROP TABLE IF EXISTS TABELA_CLASSIFICACAO_EVENTO;
DROP TABLE IF EXISTS TABELA_INSCRICAO_EVENTO;
DROP TABLE IF EXISTS TABELA_COMENTARIO;
DROP TABLE IF EXISTS TABELA_FORUM;
DROP TABLE IF EXISTS TABELA_ESTABELECIMENTOS;
DROP TABLE IF EXISTS TABELA_EVENTO;
DROP TABLE IF EXISTS TABELA_SUBAREA;
DROP TABLE IF EXISTS TABELA_COLABORADOR;
DROP TABLE IF EXISTS TABELA_ADMIN;
DROP TABLE IF EXISTS TABELA_UTILIZADOR;
DROP TABLE IF EXISTS TABELA_AREA;
DROP TABLE IF EXISTS TABELA_POSTO;



